import { defineConfig } from "drizzle-kit";
import { readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * Drizzle Kit configuration.
 *
 * Migration SQL is generated by `drizzle-kit generate` and applied to
 * Cloudflare D1 via `wrangler d1 migrations apply DB --local|--remote`. That
 * flow does not need `dbCredentials`.
 *
 * `drizzle-kit studio`, however, opens a live SQL connection — so it does.
 * For local dev, we point it at the SQLite file miniflare writes to under
 * `.wrangler/state/v3/d1/miniflare-D1DatabaseObject/`. Wrangler creates one
 * `<hash>.sqlite` per D1 binding declared in wrangler.jsonc; we pick the
 * most recently modified one, which is the DB the running dev server is
 * writing to.
 *
 * To inspect production D1 instead, run:
 *   npx wrangler d1 execute DB --remote --command "..."
 */
function findLocalD1Sqlite(): string | undefined {
    const dir = join(".wrangler", "state", "v3", "d1", "miniflare-D1DatabaseObject");
    let candidates: { path: string; mtime: number }[];
    try {
        candidates = readdirSync(dir)
            .filter((f) => f.endsWith(".sqlite") && f !== "metadata.sqlite")
            .map((f) => {
                const path = join(dir, f);
                return { path, mtime: statSync(path).mtimeMs };
            });
    } catch {
        return undefined;
    }
    if (candidates.length === 0) return undefined;
    candidates.sort((a, b) => b.mtime - a.mtime);
    return candidates[0].path;
}

const localD1 = findLocalD1Sqlite();
if (!localD1) {
    console.warn(
        "[drizzle.config] No local D1 sqlite found under .wrangler/. Run `npm run dev` at least once, or `wrangler d1 migrations apply DB --local`, so miniflare initializes the database.",
    );
}

export default defineConfig({
    dialect: "sqlite",
    schema: "./packages/shared/src/db/schema",
    out: "./packages/shared/src/db/migrations",
    casing: "snake_case",
    strict: true,
    dbCredentials: {
        url: localD1 ?? "",
    },
});
