import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Kantumruy_Pro, Open_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const kantumruyPro = Kantumruy_Pro({
    variable: "--font-kantumruy-pro",
    subsets: ["khmer", "latin"],
});

const openSans = Open_Sans({
    variable: "--font-open-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={cn("dark", "h-full", "antialiased", geistSans.variable, geistMono.variable, kantumruyPro.variable, openSans.variable, "font-sans", inter.variable)}
        >
            <body className="min-h-full flex flex-col">
                <TooltipProvider delay={200}>{children}</TooltipProvider>
                <Toaster position="top-right" richColors />
            </body>
        </html>
    );
}
